Update french translation
mateoconlechuga/cesium pull request #203
Opened 2021-12-11 21:35 UTC by Bryankaveen

2021-12-12 11:26 UTC, adriweb requested changes

2021-12-12 11:26 UTC, adriweb commented on src/strings.asm
> +	db	'Changer l',$27,'editeur de programmes',0
Accent:
```suggestion
	db	'Changer l',$27,$82,'diteur de programmes',0
```

2021-12-12 11:26 UTC, adriweb commented on src/strings.asm
> +	db	'Cacher les programmes caches',0
Accent:
```suggestion
	db	'Cacher les programmes cach',$82,'s',0
```

2021-12-12 11:26 UTC, adriweb commented on src/strings.asm
> +	db	'Appuyer <> flèches pour changer page  ',$7e,'1 sur 2]',0
Order+accent:
```suggestion
	db	'Appuyer fleches <> pour changer page  ',$7e,'1 sur 2]',0
```

2021-12-12 11:26 UTC, adriweb commented on src/strings.asm
> +	db	'Appuyer <> flèches pour changer page  ',$7e,'2 sur 2]',0
Order+accent:
```suggestion
	db	'Appuyer fleches <> pour changer page  ',$7e,'2 sur 2]',0
```

2021-12-12 11:26 UTC, adriweb commented on src/strings.asm
> +	db	'Definir mot de passe au demarrage',0
Accent:
```suggestion
	db	'D',$82,'finir mot de passe au d',$82,'marrage',0
```

2021-12-12 11:26 UTC, adriweb commented on src/strings.asm
> +	db	'Nom de l',$27,'editeur de programmes: ',0
Accent
```suggestion
	db	'Nom de l',$27,$82,'diteur de programmes: ',0
```

2021-12-12 11:29 UTC, adriweb requested changes
quite a few changes to make.

2021-12-12 11:29 UTC, adriweb commented on src/strings.asm
> +	db	'Modifier la luminosite de l'ecran',0
```suggestion
	db	'Modifier la luminosit',$82,' de l',$27,$82,'cran',0
```

2021-12-12 11:44 UTC, Bryankaveen commented
Ok, how about the "è" character?

2021-12-12 12:05 UTC, adriweb commented
Seems like it would be `$8A`.

2021-12-24 22:20 UTC, mateoconlechuga commented
Any luck on finishing this out?

2021-12-24 23:12 UTC, Bryankaveen commented
It is done :D
Merry Christmas btw ;)

Le ven. 24 déc. 2021 à 23:20, Matt Waltz ***@***.***> a
écrit :

> Any luck on finishing this out?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mateoconlechuga/cesium/pull/203#issuecomment-1000940505>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUJIUSUI6AEUS4IZJA7XVUTUSTW4HANCNFSM5J3OLCNQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2021-12-24 23:22 UTC, mateoconlechuga commented
Great thank you! Merry Christmas to you too :)

2021-12-24 23:23 UTC, merged